baseURL = "http://example.org/"
languageCode = "en-us"
title = "Kaizen Solutions Blog"
theme = "LeaveIt"

paginate = 10
enableEmoji = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    since = 2019
    author = "Kaizen Solutions"                         # Author's name
    avatar = "/images/profile.png"                      # Author's avatar
    subtitle = "The only constant is improvement"       # Subtitle
    cdn_url = ""                                        # Base CDN URL
    home_mode = ""                                      # post or other
    keywords = "functional-programming,scala"

[params.social]
    GitHub   = "kaizen-reactive-solutions"
    LinkedIn = "calvin-lee-fernandes"
    Twitter  = "cal_fern"
    Email    = "cal@kaizen-solutions.io"