[build]
publish = "public"              # default hugo build folder
command = "hugo --gc"           # hugo build command

[context.production.environment]
HUGO_VERSION = "0.72.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"